node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'Nodejs_V20') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', '8823705b-5ceb-4ff9-b345-606fe1f4fd4b	') {
       def app = docker.build("arunkumarrajan/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
